/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.Conexion;
import Clases.Visitas;
import java.net.URLDecoder;
import java.sql.Connection;
import java.sql.Time;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author panay
 */
public class FrVisitas extends javax.swing.JInternalFrame {
    
    Visitas obj= new Visitas();
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form FrVisitas
     */
    public FrVisitas() {
        initComponents();
        jcmbNomResi.setModel(obj.Residentes()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpVisitas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jbtnGuardarVisitas = new javax.swing.JButton();
        jbtnImprimirVisitas = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jtxtNomVisitante = new javax.swing.JTextField();
        jcmbNomResi = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtDui = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtxtFechaVisita = new javax.swing.JTextField();
        jtxtHora = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaDescripcion = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1160, 610));
        setPreferredSize(new java.awt.Dimension(1160, 610));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpVisitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(110, 15, 27));
        jPanel1.setForeground(new java.awt.Color(110, 15, 27));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Bodoni MT Black", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(110, 15, 27));
        jLabel2.setText("                         AÑADIR VISITAS");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 70));

        jbtnGuardarVisitas.setBackground(new java.awt.Color(51, 51, 51));
        jbtnGuardarVisitas.setFont(new java.awt.Font("Bodoni MT Black", 1, 18)); // NOI18N
        jbtnGuardarVisitas.setForeground(new java.awt.Color(255, 255, 255));
        jbtnGuardarVisitas.setText("Guardar");
        jbtnGuardarVisitas.setBorder(null);
        jbtnGuardarVisitas.setContentAreaFilled(false);
        jbtnGuardarVisitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnGuardarVisitasMouseClicked(evt);
            }
        });
        jbtnGuardarVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarVisitasActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGuardarVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, 190, 50));

        jbtnImprimirVisitas.setBackground(new java.awt.Color(51, 51, 51));
        jbtnImprimirVisitas.setFont(new java.awt.Font("Bodoni MT Black", 1, 18)); // NOI18N
        jbtnImprimirVisitas.setForeground(new java.awt.Color(255, 255, 255));
        jbtnImprimirVisitas.setText("Reporte");
        jbtnImprimirVisitas.setBorder(null);
        jbtnImprimirVisitas.setContentAreaFilled(false);
        jbtnImprimirVisitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnImprimirVisitasMouseClicked(evt);
            }
        });
        jbtnImprimirVisitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnImprimirVisitasActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnImprimirVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 450, 190, 50));

        jLabel18.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nombre de visitante");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 50));

        jtxtNomVisitante.setBackground(new java.awt.Color(102, 102, 102));
        jtxtNomVisitante.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jtxtNomVisitante.setForeground(new java.awt.Color(255, 255, 255));
        jtxtNomVisitante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 15, 27), 2));
        jPanel1.add(jtxtNomVisitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 200, 30));

        jcmbNomResi.setBackground(new java.awt.Color(102, 102, 102));
        jcmbNomResi.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jcmbNomResi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbNomResi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 15, 27), 2));
        jcmbNomResi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmbNomResiItemStateChanged(evt);
            }
        });
        jcmbNomResi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNomResiActionPerformed(evt);
            }
        });
        jPanel1.add(jcmbNomResi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 310, 30));

        jLabel13.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Nombre de residente");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 50));

        jLabel14.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DUI de visitante");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 50));

        jtxtDui.setBackground(new java.awt.Color(102, 102, 102));
        jtxtDui.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jtxtDui.setForeground(new java.awt.Color(255, 255, 255));
        jtxtDui.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 15, 27), 2));
        jPanel1.add(jtxtDui, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 200, 30));

        jLabel19.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Fecha de visita");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, 50));

        jLabel15.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Hora de visita");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, -1, 50));

        jtxtFechaVisita.setBackground(new java.awt.Color(102, 102, 102));
        jtxtFechaVisita.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jtxtFechaVisita.setForeground(new java.awt.Color(255, 255, 255));
        jtxtFechaVisita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 15, 27), 2));
        jPanel1.add(jtxtFechaVisita, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 120, 200, 30));

        jtxtHora.setBackground(new java.awt.Color(102, 102, 102));
        jtxtHora.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jtxtHora.setForeground(new java.awt.Color(255, 255, 255));
        jtxtHora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 15, 27), 2));
        jPanel1.add(jtxtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 180, 200, 30));

        jLabel17.setFont(new java.awt.Font("Bodoni MT Black", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Descripcion de visita");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 50));

        jtxtaDescripcion.setBackground(new java.awt.Color(102, 102, 102));
        jtxtaDescripcion.setColumns(20);
        jtxtaDescripcion.setFont(new java.awt.Font("Bodoni MT Black", 0, 14)); // NOI18N
        jtxtaDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        jtxtaDescripcion.setRows(5);
        jtxtaDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(110, 15, 27), 2));
        jScrollPane1.setViewportView(jtxtaDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 240, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/disquete-de-guardar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/historial-medico.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 380, -1, -1));

        jpVisitas.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 640));

        getContentPane().add(jpVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int Nombre=0;
    private void jbtnGuardarVisitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnGuardarVisitasMouseClicked
        // TODO add your handling code here:
        if(jtxtNomVisitante.getText().isEmpty() ){
            JOptionPane.showMessageDialog(this, "Campos Vacios","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
                obj.setNomVisitante(jtxtNomVisitante.getText());
                obj.setDUIVisitante(jtxtDui.getText());
                obj.setDescripcion(jtxtaDescripcion.getText());
                obj.setHoraVisita((Time) jtxtHora.getAction());
                obj.setFechaVisita(jtxtFechaVisita.getText());
                obj.setIdResidente(Nombre);
              
                                
                if(obj.guardarVisita()){
                    JOptionPane.showMessageDialog(this, "Datos guardado correctamente","CORRECTO", JOptionPane.INFORMATION_MESSAGE);
   
                }
                else{
                    JOptionPane.showMessageDialog(this, "Error, no se guardado", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }

    }//GEN-LAST:event_jbtnGuardarVisitasMouseClicked

    private void jbtnGuardarVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarVisitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnGuardarVisitasActionPerformed

    private void jbtnImprimirVisitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnImprimirVisitasMouseClicked
        // TODO add your handling code here:
        String path="";
        try{
            path=getClass().getResource("/Reportes/Visitas.jasper").getPath();
            path=URLDecoder.decode(path, "UTF-8");
            Connection cn = Conexion.getConexion();
            Map parametros=new HashMap();
            JasperReport reporte=(JasperReport)JRLoader.loadObject(path);
            JasperPrint imprimir= JasperFillManager.fillReport(reporte,parametros,cn);
            JasperViewer visor=new JasperViewer(imprimir,false);
            visor.setTitle("Reporte de visitas");
            visor.setVisible(true);
        }catch(Exception ex){
            System.out.println(ex.getMessage());
        
        }

    }//GEN-LAST:event_jbtnImprimirVisitasMouseClicked

    private void jbtnImprimirVisitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImprimirVisitasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jbtnImprimirVisitasActionPerformed

    private void jcmbNomResiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmbNomResiItemStateChanged
        // TODO add your handling code here:

        Nombre = obj.idResidente(jcmbNomResi.getSelectedItem());
    }//GEN-LAST:event_jcmbNomResiItemStateChanged

    private void jcmbNomResiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNomResiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbNomResiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnGuardarVisitas;
    private javax.swing.JButton jbtnImprimirVisitas;
    private javax.swing.JComboBox<String> jcmbNomResi;
    private javax.swing.JPanel jpVisitas;
    private javax.swing.JTextField jtxtDui;
    private javax.swing.JTextField jtxtFechaVisita;
    private javax.swing.JTextField jtxtHora;
    private javax.swing.JTextField jtxtNomVisitante;
    private javax.swing.JTextArea jtxtaDescripcion;
    // End of variables declaration//GEN-END:variables
}
